# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='Name of the service.', max_length=100, unique=True)),
                ('host', models.URLField(editable=False, help_text='URL of the service. Ex. https://auth.example.com/', unique=True)),
                ('is_available', models.NullBooleanField(default=None, editable=False, help_text='True if the service can be reached.')),
            ],
            options={
                'ordering': ['name', 'host'],
            },
        ),
    ]
